In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [5]:
type(np.array((1,2,3,4,5)))

numpy.ndarray

In [6]:
a = np.array([1,2,3,4,5])

b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [7]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
np.array(range(2,11,2))

array([ 2,  4,  6,  8, 10])

In [10]:
np.array([i for i in range(11) if i%2==0])

array([ 0,  2,  4,  6,  8, 10])

In [16]:
ar0 = np.array([1,1.5,3,4.5,'5'])
ar0.dtype

dtype('<U32')

In [14]:
ar1 = np.array(range(10))
ar1.dtype

dtype('int32')

In [15]:
ar2 = np.array([1,2,3.12,4,5])
ar2.dtype

dtype('float64')

In [18]:
ar3 = np.array([
    [1,2,3],
    ('a','b','c'),
])
ar3

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

In [20]:
ar4 = np.array([
    [1,2,3],
    ('a','b','c','d'),
],dtype=object)
ar4

array([list([1, 2, 3]), ('a', 'b', 'c', 'd')], dtype=object)

In [21]:
ar4.ndim

1

In [22]:
ar4.shape

(2,)

In [23]:
np.array([1,2,3,4,5],dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [24]:
np.array([1.1,2.5,3.8,4,5],dtype='int')

array([1, 2, 3, 4, 5])

In [26]:
a = np.array([1,2,3,4,5,])
b = np.array(a)
print('a:', id(a),' b:', id(b))
print('='*40)

a: 2223680074256  b: 2223681502928


In [27]:
b[0] = 10
print('a:', a,' b:', b)
print('='*40)

a: [1 2 3 4 5]  b: [10  2  3  4  5]


In [29]:
a = np.array([1,2,3,4,5,])
b = np.array(a,copy=False)
print('a:', id(a),' b:', id(b))
print('='*40)
b[0] = 10
print('a:', a,' b:', b)

a: 2223681502928  b: 2223681502928
a: [10  2  3  4  5]  b: [10  2  3  4  5]


In [32]:
a = np.array([1,2,3,4,5,])
print(a)

a = np.array([1,2,3,4,5,], ndmin = 2) 
a
print(a)

[1 2 3 4 5]
[[1 2 3 4 5]]


In [34]:
a = np.mat([1,2,3,4])
print(type(a))

at = np.array(a, subok=True)
af = np.array(a, )
print('at, subok=True:', type(at))
print('af, subok=False:', type(af))
print(id(at),id(af))


<class 'numpy.matrix'>
at, subok=True: <class 'numpy.matrix'>
af, subok=False: <class 'numpy.ndarray'>
2223700561872 2223680065040


In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(3.1)

array([0., 1., 2., 3.])

In [40]:
range(3.1)

TypeError: 'float' object cannot be interpreted as an integer

In [41]:
x= np.arange(5,dtype='float32')
x

array([0., 1., 2., 3., 4.], dtype=float32)

In [42]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [44]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [45]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [49]:
a = np.arange(0,200+1,3)
a.shape
len(a)

67

In [50]:
np.arange(0.1,0.4,0.1)

array([0.1, 0.2, 0.3, 0.4])